import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react'
import Navbar from '../components/Navbar/Navbar'
import client from '../apollo-client.js'
import { gql } from '@apollo/client'
import Entry from '../components/Entry/Entry'


export default function Index({ entries }) {
  return (
    <>
      <Head>
        <title>Portfolio&sup2;</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="p-8 sm:p-24  bg-gradient-to-br from-gray-800 to-black">
        <div className="mx-auto max-w-6xl">
          {/* <div style={{width: '30px', borderRadius: '5px', overflow: 'hidden'}}>
          <Image src={'/images/WICKED.png'} layout='fill' objectFit='contain'/>
        </div> */}
          <div className="flex justify-between">
            <div className="flex flex-col">
              <div className="text-[4rem] sm:text-[6rem]">
                Marek Zakrzewski
              </div>
              <div className="text-[2rem] text-gray-500">
                Developer
              </div>
            </div>
            <div className="relative w-64 h-64">
              <Image
                alt="wicked"
                src="/images/WICKED.png"
                layout="fill"
                objectFit="contain"
              />
            </div>
          </div>

          <div id="apps">
            <div className="py-2 text-header">Have a look at some of my apps</div>
            <div className="grid w-fit grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-10">
              {entries.map((entry, index) => {
                return <Entry key={index} entry={entry} />
              })}
            </div>
          </div>
          <div id="experience" className="my-12 text-header">Experience</div>
          <div id="experience" className="my-12 text-header">Skills</div>
          <div id="experience" className="my-12 text-header">Education</div>
          <div id="experience" className="my-12 text-header">Certifications</div>

          <footer className={styles.footer}>
            Marek Zakrzewski
          </footer>
        </div>
      </div>
    </>
  )
}

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
    query {
      appDescriptionCollection {
        items {
          title
          shortDescription
          fullDescription
          thumbnail {
            url
          }
          gitHubLink
          hostedLink
        }
      }
    }
    `
  })
  const items = data.appDescriptionCollection.items
  console.log(items)
  return {
    props: {
      entries: items
    }
  }

}